---
title: "Einstaklingverkefni 1 stæ203"
author: "Ásgerður Júlía"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Liður 1: Nafnið þitt

Hugsaðu þér að þú hafir skrifað allt nafnið þitt (fullt nafn) með skrafltöflum og sett í poka.

a)  Þú dregur einn staf af handahófi upp úr pokanum. Hverjar eru líkurnar á því að þú dragir fyrsta stafinn í fyrsta nafninu þínu?

Svar: Fullt nafn - Ásgerður Júlía Gunnarsdóttir 1/26

b)  Gerum ráð fyrir að fyrsti stafurinn sem þú dróst hafi einmitt verið fyrsti stafurinn í nafninu þínu. Þú heldur áfram að draga eins marga stafi og eru í fyrsta nafninu þínu, án þess að skila þeim aftur í pokann. Hverjar eru líkurnar á því að þú dragir fyrsta nafnið þitt (í sömu röð og þú dregur upp stafina)?

Svar: 1\* 2/25 \* 2/24 \* 1/23 \* 4/22 \* 1/21 \* 2/20 \* 3/19

## Liður 2: Monty Hall þrautin

Ímyndaðu þér að þú sért að taka þátt í leik í sjónvarpsþætti og fáir val um þrjár hurðir til að opna. Á bak við eina hurð er bíll, á bak við hinar tvær geitur. Þú velur hurð og þá gengur gestgjafinn, sem veit hvað er á bak við hurðirnar, að annarri hurð, opnar hana, og geit birtist. Þá segir þáttastjórnandinn við þig: "Viltu breyta valinu?"

Færið rök fyrir því hvers vegna þú átt að breyta valinu á hurð.

Svar: Við höfum 3 mismunandi lausnir hvar bíllin er, bak við hurð 1,2, eða 3. Við ætlum að skipta um hurð alltaf. Við veljum hurð nr 1 og skiptum þegar hann opnar aðrahvora hurðina, 2,eða 3. líkurnar á því að við völdum hurð með geit í upphafi eru 2/3, svo ef við skiptum um hurð er 1/3 líkur á að við fáum núna geit, en eft við skiptum ekki eru ennþá 2/3 líkur á geit.
